changing makefile

diff --git a/src/hvlTop/tb/makefile b/src/hvlTop/tb/makefile
--- a/src/hvlTop/tb/makefile
+++ b/src/hvlTop/tb/makefile
@@ -36,18 +36,18 @@ compile:
 	make clean_compile;
 	make clean_simulate;
 	vlib work;
-	vlog -sv \
-	+acc \
-	+cover \
-	+fcover \
-	$(comp_args) \
-	-l AhbCoverPropertyCompile.log \
-	-f ./ahbCoverProperty.f;
+	vlog -sv +acc +cover +fcover $(comp_args) -l AhbCoverPropertyCompile.log -f ./ahbCoverProperty.f;
+	vlog -sv +acc +cover +fcover $(comp_args) -l AhbMasterAssertionsCompile.log -f ./ahbAssertion.f;
+	vlog -sv +acc +cover +fcover $(comp_args) -l AhbSlaveAssertionsCompile.log -f ./ahbAssertion.f;
 	make compile_war_err;
+	make compile_war_err_sassert;
+	make compile_war_err_massert;
+
+
 
 # Default test configuration
 ifndef test
-override test = AhbCoverPropertyTb
+tests = AhbCoverPropertyTb AhbMasterAssertionTb AhbSlaveAssertionTb
 endif
 
 # Default verbosity level
@@ -60,29 +60,35 @@ ifndef test_folder
 override test_folder = $(test)
 endif
 
-# Simulation target
 simulate:
-	mkdir -p $(test_folder);
-	vsim -vopt \
-	work.$(test) \
-	-voptargs=+acc=npr \
-	-assertdebug \
-	+UVM_TESTNAME=$(test) \
-	+UVM_VERBOSITY=$(uvm_verbosity) \
-	-l $(test_folder)/$(test).log \
-	-sva \
-	-coverage \
-	-c -do "log -r /*; add wave -r /*; coverage save -onexit -assert -directive -cvg -codeAll $(test_folder)/$(test_folder)_coverage.ucdb; run -all; exit" \
-	-wlf $(test_folder)/waveform.wlf;
-	make simulate_war_err;
+	@for t in $(tests); do \
+		mkdir -p $$t; \
+		vsim -vopt \
+		work.$$t \	
+		-voptargs=+acc=npr \
+		-assertdebug \
+		+UVM_TESTNAME=$$t \
+		+UVM_VERBOSITY=$(uvm_verbosity) \
+		-l $$t/$$t.log \
+		-sva \
+		-coverage \
+		-c -do "log -r /*; add wave -r /*; coverage save -onexit -assert -directive -cvg -codeAll $$t/coverage.ucdb; run -all; exit" \
+		-wlf $$t/waveform.wlf; \
+		make simulate_war_err test=$$t; \
+		make simulate_war_err_sassert test=$$t; \
+		make simulate_war_err_massert test=$$t; \
+	done
 
 # Cleanup rules
 clean_simulate:
-	rm -rf *_test*;
+	rm -rf AhbCoverPropertyTb AhbMasterAssertionTb AhbSlaveAssertionTb;
+	rm -rf *_test/ *_test.log;  # Be more specific if needed
 
 clean_compile:
-	rm -rf work/ *_compile.log transcript waveform.wlf;
+	rm -rf work/ *.log transcript waveform.wlf;
 	rm -rf merged_coverage.ucdb merged_cov_html_report;
+	rm -rf *.ucdb *.wlf;  # Remove any leftover coverage and waveform files
+
 
 # Coverage merge and reporting
 merge_cov_report:
@@ -95,52 +101,58 @@ merge_cov_report:
 	echo "-----------------------------------------------------------------";
 	echo "";
 
-# Compilation warning/error check
-compile_war_err:
-	echo "";
-	echo "-----------------------------------------------------------------";
-	echo "------------------- Compilation Report --------------------------";
-	echo "";
-	grep "^** " AhbCoverPropertyCompile.log;
-	echo "";
-	grep "^Error" AhbCoverPropertyCompile.log;
-	echo "";
-	grep "^Info" AhbCoverPropertyCompile.log;
-	echo "";
-	echo "Log file path: AhbCoverPropertyCompile.log";
-	echo "";
-	echo "-----------------------------------------------------------------";
-	echo "-----------------------------------------------------------------";
-	echo "";
 
-# Simulation warning/error check
+# Compilation warning/error check (covers all tests)
+compile_war_err:
+	@for log in AhbCoverPropertyCompile.log AhbMasterAssertionsCompile.log AhbSlaveAssertionsCompile.log; do \
+		echo ""; \
+		echo "-----------------------------------------------------------------"; \
+		echo "------------------- Compilation Report ($$log) -----------------"; \
+		echo ""; \
+		grep "^** " $$log || true; \
+		echo ""; \
+		grep "^Error" $$log || true; \
+		echo ""; \
+		grep "^Info" $$log || true; \
+		echo ""; \
+		echo "Log file path: $$log"; \
+		echo ""; \
+		echo "-----------------------------------------------------------------"; \
+		echo "-----------------------------------------------------------------"; \
+		echo ""; \
+	done
+
+# Simulation warning/error check (covers all tests)
 simulate_war_err:
-	echo "";
-	echo "-----------------------------------------------------------------";
-	echo "-------------------- Simulation Report --------------------------";
-	echo "";
-	echo "Simulator Errors";
-	grep "Error" $(test_folder)/$(test).log;
-	echo "";
-	grep "Info" $(test_folder)/$(test).log;
-	echo "";
-	echo "UVM Fatal";
-	grep "UVM_FATAL" $(test_folder)/$(test).log;
-	echo "";
-	echo "UVM Errors";
-	grep "UVM_ERROR" $(test_folder)/$(test).log;
-	echo "";
-	echo "UVM Warnings";
-	grep "UVM_WARNING" $(test_folder)/$(test).log;
-	echo "";
-	echo "Testname: $(test)";
-	echo "";
-	echo "Log file path: $(test_folder)/$(test).log";
-	echo "";
-	echo "Waveform: vsim -view $(test_folder)/waveform.wlf &";
-	echo "";
-	echo "Coverage report: firefox $(test_folder)/html_cov_report/index.html &";
-	echo "";
-	echo "-----------------------------------------------------------------";
-	echo "-----------------------------------------------------------------";
-	echo "";
+	@for t in $(tests); do \
+		echo ""; \
+		echo "-----------------------------------------------------------------"; \
+		echo "-------------------- Simulation Report for $$t -----------------"; \
+		echo ""; \
+		echo "Simulator Errors"; \
+		grep "Error" $$t/$$t.log || true; \
+		echo ""; \
+		grep "Info" $$t/$$t.log || true; \	
+		echo ""; \
+		echo "UVM Fatal"; \
+    		grep "UVM_FATAL" $$t/$$t.log || true; \
+    		echo ""; \
+    		echo "UVM Errors"; \
+    		grep "UVM_ERROR" $$t/$$t.log || true; \
+    		echo ""; \
+    		echo "UVM Warnings"; \
+    		grep "UVM_WARNING" $$t/$$t.log || true; \
+    		echo ""; \
+    		echo "Testname: $$t"; \
+    		echo ""; \
+    		echo "Log file path: $$t/$$t.log"; \
+    		echo ""; \
+    		echo "Waveform: vsim -view $$t/waveform.wlf &"; \
+    		echo ""; \
+    		echo "Coverage report: firefox $$t/html_cov_report/index.html &"; \
+    		echo ""; \
+    		echo "-----------------------------------------------------------------"; \
+    		echo "-----------------------------------------------------------------"; \
+    		echo ""; \
+  	done
+
