Update Makefile

diff --git a/src/hvlTop/tb/Makefile b/src/hvlTop/tb/Makefile
--- a/src/hvlTop/tb/Makefile
+++ b/src/hvlTop/tb/Makefile
@@ -1,5 +1,3 @@
-# Makefile for AHB Master Assertions Testbench
-
 # Default target
 usage:
 	echo "";
@@ -26,11 +24,11 @@ usage:
 	echo "-----------------------------------------------------------------";
 	echo "-----------------------------------------------------------------";
 	echo "";
-
+ 
 # Default action
 all:
 	make clean; make compile; make simulate;
-
+ 
 # Compilation target
 compile:
 	make clean_compile;
@@ -43,23 +41,23 @@ compile:
 	$(comp_args) \
 	-l AhbCoverPropertyCompile.log \
 	-f ./ahbCoverProperty.f;
-	Make compile_war_err;
-
+	make compile_war_err;
+ 
 # Default test configuration
 ifndef test
 override test = AhbCoverPropertyTb
 endif
-
+ 
 # Default verbosity level
 ifndef uvm_verbosity
 override uvm_verbosity = UVM_MEDIUM
 endif
-
+ 
 # Default test folder
 ifndef test_folder
 override test_folder = $(test)
 endif
-
+ 
 # Simulation target
 simulate:
 	mkdir -p $(test_folder);
@@ -72,18 +70,18 @@ simulate:
 	-l $(test_folder)/$(test).log \
 	-sva \
 	-coverage \
-	-c -do "log -r /*; add wave -r /*; coverage save -onexit -assert -directive -cvg -codeAll $(test_folder)/$(test_folder)_coverage.ucdb; run -all; exit" \
+	-c -do "log -r /*; add wave -r /*; coverage save -onexit -assert -directive -cvg -codeAll $(test_folder)/$(test_folder)_coverage.ucdb; run -all; quit -sim;" \
 	-wlf $(test_folder)/waveform.wlf;
 	make simulate_war_err;
-
+ 
 # Cleanup rules
 clean_simulate:
-	rm -rf *_test*;
-
+	rm -rf *_test* */*.ucdb;
+ 
 clean_compile:
 	rm -rf work/ *_compile.log transcript waveform.wlf;
 	rm -rf merged_coverage.ucdb merged_cov_html_report;
-
+ 
 # Coverage merge and reporting
 merge_cov_report:
 	rm -rf merged_coverage.ucdb merged_cov_html_report;
@@ -91,56 +89,49 @@ merge_cov_report:
 	vcover report -html merged_coverage.ucdb -htmldir ./merged_cov_html_report -details;
 	echo "";
 	echo "-----------------------------------------------------------------";
-	echo "Coverage report: firefox merged_cov_html_report/index.html &";
+	if command -v firefox >/dev/null; then \
+		echo "Coverage report: firefox merged_cov_html_report/index.html &"; \
+	else \
+		echo "Coverage report available at: merged_cov_html_report/index.html"; \
+	fi
 	echo "-----------------------------------------------------------------";
 	echo "";
-
+ 
 # Compilation warning/error check
 compile_war_err:
 	echo "";
 	echo "-----------------------------------------------------------------";
 	echo "------------------- Compilation Report --------------------------";
 	echo "";
-	grep "^** " AhbCoverPropertyCompile.log;
-	echo "";
-	grep "^Error" AhbCoverPropertyCompile.log;
-	echo "";
-	grep "^Info" AhbCoverPropertyCompile.log;
+	@if [ -f AhbCoverPropertyCompile.log ]; then \
+		grep "^** " AhbCoverPropertyCompile.log || true; \
+		grep "^Error" AhbCoverPropertyCompile.log || true; \
+		grep "^Info" AhbCoverPropertyCompile.log || true; \
+	else \
+		echo "No compilation log found."; \
+	fi
 	echo "";
 	echo "Log file path: AhbCoverPropertyCompile.log";
 	echo "";
 	echo "-----------------------------------------------------------------";
 	echo "-----------------------------------------------------------------";
 	echo "";
-
+ 
 # Simulation warning/error check
 simulate_war_err:
 	echo "";
 	echo "-----------------------------------------------------------------";
 	echo "-------------------- Simulation Report --------------------------";
 	echo "";
-	echo "Simulator Errors";
-	grep "Error" $(test_folder)/$(test).log;
-	echo "";
-	grep "Info" $(test_folder)/$(test).log;
-	echo "";
-	echo "UVM Fatal";
-	grep "UVM_FATAL" $(test_folder)/$(test).log;
-	echo "";
-	echo "UVM Errors";
-	grep "UVM_ERROR" $(test_folder)/$(test).log;
-	echo "";
-	echo "UVM Warnings";
-	grep "UVM_WARNING" $(test_folder)/$(test).log;
-	echo "";
-	echo "Testname: $(test)";
-	echo "";
-	echo "Log file path: $(test_folder)/$(test).log";
-	echo "";
-	echo "Waveform: vsim -view $(test_folder)/waveform.wlf &";
-	echo "";
-	echo "Coverage report: firefox $(test_folder)/html_cov_report/index.html &";
-	echo "";
-	echo "-----------------------------------------------------------------";
-	echo "-----------------------------------------------------------------";
-	echo "";
+	@if [ -f $(test_folder)/$(test).log ]; then \
+		echo "Simulator Errors"; \
+		grep "Error" $(test_folder)/$(test).log || true; \
+		grep "Info" $(test_folder)/$(test).log || true; \
+		echo "UVM Fatal"; \
+		grep "UVM_FATAL" $(test_folder)/$(test).log || true; \
+		echo "UVM Errors"; \
+		grep "UVM_ERROR" $(test_folder)/$(test).log || true; \
+		echo "UVM Warnings"; \
+		grep "UVM_WARNING" $(test_folder)/$(test).log || true; \
+	else \
+		echo "No sim
